export interface Language {
  apiName: string; // English name
  displayName: string; // Native name or commonly used name
}

// Languages that use non-Latin scripts and benefit from romanization
const LANGUAGES_NEEDING_ROMANIZATION = new Set([
  "Japanese",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Korean",
  "Thai",
  "Vietnamese",
  "Hindi",
  "Bengali",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Arabic",
  "Persian",
  "Urdu",
  "Hebrew",
  "Russian",
  "Ukrainian",
  "Belarusian",
  "Bulgarian",
  "Georgian",
  "Armenian",
  "Mongolian",
  "Myanmar (Burmese)",
  "Khmer",
  "Lao",
  "Tibetan",
  "Nepali",
  "Sinhala",
  "Gujarati",
  "Punjabi (Gurmukhi)",
  "Punjabi (Shahmukhi)",
  "Marathi",
  "Sanskrit",
  "Odia (Oriya)",
  "Greek",
]);

export const needsRomanization = (language: Language): boolean => {
  return LANGUAGES_NEEDING_ROMANIZATION.has(language.apiName);
};

export const languages: Language[] = [
  { apiName: "Automatic", displayName: "Automatic" },
  { apiName: "Abkhaz", displayName: "Аҧсуа" },
  { apiName: "Acehnese", displayName: "Aceh" },
  { apiName: "Acholi", displayName: "Luo" },
  { apiName: "Afar", displayName: "Afaraf" },
  { apiName: "Afrikaans", displayName: "Afrikaans" },
  { apiName: "Albanian", displayName: "Shqip" },
  { apiName: "Alur", displayName: "Alur" },
  { apiName: "Amharic", displayName: "አማርኛ" },
  { apiName: "Arabic", displayName: "العربية" },
  { apiName: "Armenian", displayName: "Հայերեն" },
  { apiName: "Assamese", displayName: "অসমীয়া" },
  { apiName: "Avar", displayName: "авар" },
  { apiName: "Awadhi", displayName: "अवधी" },
  { apiName: "Aymara", displayName: "Aymara" },
  { apiName: "Azerbaijani", displayName: "Azərbaycanca" },
  { apiName: "Balinese", displayName: "Bali" },
  { apiName: "Baluchi", displayName: "بلوچی" },
  { apiName: "Bambara", displayName: "Bamanankan" },
  { apiName: "Baoulé", displayName: "Baoulé" },
  { apiName: "Bashkir", displayName: "башҡорт" },
  { apiName: "Basque", displayName: "Euskara" },
  { apiName: "Batak Karo", displayName: "Karo Batak" },
  { apiName: "Batak Simalungun", displayName: "Simalungun Batak" },
  { apiName: "Batak Toba", displayName: "Toba Batak" },
  { apiName: "Belarusian", displayName: "Беларуская" },
  { apiName: "Bemba", displayName: "Icibemba" },
  { apiName: "Bengali", displayName: "বাংলা" },
  { apiName: "Betawi", displayName: "Betawi" },
  { apiName: "Bhojpuri", displayName: "भोजपुरी" },
  { apiName: "Bikol", displayName: "Bikol" },
  { apiName: "Bosnian", displayName: "Bosanski" },
  { apiName: "Breton", displayName: "Brezhoneg" },
  { apiName: "Bulgarian", displayName: "Български" },
  { apiName: "Buryat", displayName: "Буряад" },
  { apiName: "Cantonese", displayName: "广东话" },
  { apiName: "Catalan", displayName: "Català" },
  { apiName: "Cebuano", displayName: "Cebuano" },
  { apiName: "Chamorro", displayName: "Chamoru" },
  { apiName: "Chechen", displayName: "Нохчийн" },
  { apiName: "Chichewa", displayName: "Chichewa" },
  { apiName: "Chinese (Simplified)", displayName: "简体中文" },
  { apiName: "Chinese (Traditional)", displayName: "繁體中文" },
  { apiName: "Chuukese", displayName: "Chukchi" },
  { apiName: "Chuvash", displayName: "Чăваш" },
  { apiName: "Corsican", displayName: "Corsu" },
  { apiName: "Crimean Tatar", displayName: "Qırım Tatarca" },
  { apiName: "Croatian", displayName: "Hrvatski" },
  { apiName: "Czech", displayName: "Čeština" },
  { apiName: "Danish", displayName: "Dansk" },
  { apiName: "Dari", displayName: "دری" },
  { apiName: "Dhivehi", displayName: "ދިވެހި" },
  { apiName: "Dinka", displayName: "Dinka" },
  { apiName: "Dogri", displayName: "डोगरी" },
  { apiName: "Dombe", displayName: "Dombe" },
  { apiName: "Dutch", displayName: "Nederlands" },
  { apiName: "Dyula", displayName: "Jula" },
  { apiName: "Dzongkha", displayName: "རྫོང་ཁ" },
  { apiName: "English", displayName: "English" },
  { apiName: "Esperanto", displayName: "Esperanto" },
  { apiName: "Estonian", displayName: "Eesti" },
  { apiName: "Ewe", displayName: "Eʋegbe" },
  { apiName: "Faroese", displayName: "Føroyskt" },
  { apiName: "Fijian", displayName: "Na Vosa Vakaviti" },
  { apiName: "Filipino", displayName: "Filipino" },
  { apiName: "Finnish", displayName: "Suomi" },
  { apiName: "Fon", displayName: "Fɔngbè" },
  { apiName: "French", displayName: "Français" },
  { apiName: "Frisian", displayName: "Frysk" },
  { apiName: "Friulian", displayName: "Furlan" },
  { apiName: "Fulani", displayName: "Fulfulde" },
  { apiName: "Ga", displayName: "Gã" },
  { apiName: "Galician", displayName: "Galego" },
  { apiName: "Georgian", displayName: "ქართული" },
  { apiName: "German", displayName: "Deutsch" },
  { apiName: "Greek", displayName: "Ελληνικά" },
  { apiName: "Guarani", displayName: "Aña" },
  { apiName: "Gujarati", displayName: "ગુજરાતી" },
  { apiName: "Haitian Creole", displayName: "Kreyòl Ayisyen" },
  { apiName: "Hakha Chin", displayName: "Hakha" },
  { apiName: "Hausa", displayName: "Hausa" },
  { apiName: "Hawaiian", displayName: "ʻŌlelo Hawaiʻi" },
  { apiName: "Hebrew", displayName: "עברית" },
  { apiName: "Hiligaynon", displayName: "Ilonggo" },
  { apiName: "Hindi", displayName: "हिन्दी" },
  { apiName: "Hmong", displayName: "Hmoob" },
  { apiName: "Hungarian", displayName: "Magyar" },
  { apiName: "Hunsrik", displayName: "Hunsrückisch" },
  { apiName: "Iban", displayName: "Iban" },
  { apiName: "Icelandic", displayName: "Íslenska" },
  { apiName: "Igbo", displayName: "Igbo" },
  { apiName: "Ilocano", displayName: "Ilokano" },
  { apiName: "Indonesian", displayName: "Bahasa Indonesia" },
  { apiName: "Irish", displayName: "Gaeilge" },
  { apiName: "Italian", displayName: "Italiano" },
  { apiName: "Jamaican Patois", displayName: "Jamaican Patois" },
  { apiName: "Japanese", displayName: "日本語" },
  { apiName: "Javanese", displayName: "ꦧꦱꦗꦮ" },
  { apiName: "Jingpo", displayName: "Jinghpaw" },
  { apiName: "Kalaallisut", displayName: "Kalaallisut" },
  { apiName: "Kannada", displayName: "ಕನ್ನಡ" },
  { apiName: "Kanuri", displayName: "Kanuri" },
  { apiName: "Kapampangan", displayName: "Kapampangan" },
  { apiName: "Kazakh", displayName: "Қазақ" },
  { apiName: "Khasi", displayName: "Ka Khasi" },
  { apiName: "Khmer", displayName: "ខ្មែរ" },
  { apiName: "Kiga", displayName: "Ikiga" },
  { apiName: "Kikongo", displayName: "Kikongo" },
  { apiName: "Kinyarwanda", displayName: "Kinyarwanda" },
  { apiName: "Kituba", displayName: "Kituba" },
  { apiName: "Kokborok", displayName: "ꯀꯧꯇꯩ" },
  { apiName: "Komi", displayName: "Коми" },
  { apiName: "Konkani", displayName: "कोंकणी" },
  { apiName: "Korean", displayName: "한국어" },
  { apiName: "Krio", displayName: "Krio" },
  { apiName: "Kurdish (Kurmanji)", displayName: "Kurdî (Kurmanjî)" },
  { apiName: "Kurdish (Sorani)", displayName: "��وردی (سۆرانی)" },
  { apiName: "Kyrgyz", displayName: "Кыргыз" },
  { apiName: "Lao", displayName: "ລາວ" },
  { apiName: "Latgalian", displayName: "Latgaļu" },
  { apiName: "Latin", displayName: "Latina" },
  { apiName: "Latvian", displayName: "Latviešu" },
  { apiName: "Ligurian", displayName: "Ligurian" },
  { apiName: "Limburgish", displayName: "Limburgs" },
  { apiName: "Lingala", displayName: "Lingála" },
  { apiName: "Lithuanian", displayName: "Lietuvių" },
  { apiName: "Lombard", displayName: "Lombard" },
  { apiName: "Luganda", displayName: "Luganda" },
  { apiName: "Luo", displayName: "Dholuo" },
  { apiName: "Luxembourgish", displayName: "Lëtzebuergesch" },
  { apiName: "Macedonian", displayName: "Македонски" },
  { apiName: "Madurese", displayName: "Madhura" },
  { apiName: "Maithili", displayName: "मैथिली" },
  { apiName: "Makassar", displayName: "Makasar" },
  { apiName: "Malagasy", displayName: "Malagasy" },
  { apiName: "Malay", displayName: "Bahasa Melayu" },
  { apiName: "Malay (Jawi)", displayName: "بهاس ملايو" },
  { apiName: "Malayalam", displayName: "മലയാളം" },
  { apiName: "Maltese", displayName: "Malti" },
  { apiName: "Mam", displayName: "Mam" },
  { apiName: "Manx", displayName: "Gaelg" },
  { apiName: "Maori", displayName: "Māori" },
  { apiName: "Marathi", displayName: "मराठी" },
  { apiName: "Marshallese", displayName: "Kajin Majōl" },
  { apiName: "Marwadi", displayName: "मारवाड़ी" },
  { apiName: "Mauritian Creole", displayName: "Kreol Morisyen" },
  { apiName: "Meadow Mari", displayName: "Мари" },
  { apiName: "Meiteilon (Manipuri)", displayName: "মৈতৈলোন" },
  { apiName: "Minang", displayName: "Minangkabau" },
  { apiName: "Mizo", displayName: "Mizo" },
  { apiName: "Mongolian", displayName: "Монгол" },
  { apiName: "Myanmar (Burmese)", displayName: "ဗမာစာ" },
  { apiName: "Nahuatl (Eastern Huasteca)", displayName: "Nāhuatl" },
  { apiName: "Ndau", displayName: "Ndau" },
  { apiName: "Ndebele (South)", displayName: "isiNdebele" },
  { apiName: "Nepalbhasa (Newari)", displayName: "नेपाल भाषा" },
  { apiName: "Nepali", displayName: "नेपाली" },
  { apiName: "NKo", displayName: "N'Ko" },
  { apiName: "Norwegian", displayName: "Norsk" },
  { apiName: "Nuer", displayName: "Nuer" },
  { apiName: "Occitan", displayName: "Occitan" },
  { apiName: "Odia (Oriya)", displayName: "ଓଡ଼ିଆ" },
  { apiName: "Oromo", displayName: "Afaan Oromoo" },
  { apiName: "Ossetian", displayName: "Ирон" },
  { apiName: "Pangasinan", displayName: "Pangasinan" },
  { apiName: "Papiamento", displayName: "Papiamentu" },
  { apiName: "Pashto", displayName: "پښتو" },
  { apiName: "Persian", displayName: "فارسی" },
  { apiName: "Polish", displayName: "Polski" },
  { apiName: "Portuguese (Brazil)", displayName: "Português (Brasil)" },
  { apiName: "Portuguese (Portugal)", displayName: "Português (Portugal)" },
  { apiName: "Punjabi (Gurmukhi)", displayName: "ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)" },
  { apiName: "Punjabi (Shahmukhi)", displayName: "پنجابی (شاہ مکھی)" },
  { apiName: "Quechua", displayName: "Runa Simi" },
  { apiName: "Qʼeqchiʼ", displayName: "Qʼeqchiʼ" },
  { apiName: "Romani", displayName: "Romani" },
  { apiName: "Romanian", displayName: "Română" },
  { apiName: "Rundi", displayName: "Kirundi" },
  { apiName: "Russian", displayName: "Русский" },
  { apiName: "Sami (North)", displayName: "Sámegiella" },
  { apiName: "Samoan", displayName: "Gagana Samoa" },
  { apiName: "Sango", displayName: "Sängö" },
  { apiName: "Sanskrit", displayName: "संस्कृतम्" },
  { apiName: "Santali", displayName: "Santali" },
  { apiName: "Scots Gaelic", displayName: "Gàidhlig" },
  { apiName: "Sepedi", displayName: "Sepedi" },
  { apiName: "Serbian", displayName: "Српски" },
  { apiName: "Sesotho", displayName: "Sesotho" },
  { apiName: "Seychellois Creole", displayName: "Kreol Seselwa" },
  { apiName: "Shan", displayName: "ၽႃႇႈ" },
  { apiName: "Shona", displayName: "ChiShona" },
  { apiName: "Sicilian", displayName: "Sicilianu" },
  { apiName: "Silesian", displayName: "Ślōnskŏ" },
  { apiName: "Sindhi", displayName: "سنڌي" },
  { apiName: "Sinhala", displayName: "සිංහල" },
  { apiName: "Slovak", displayName: "Slovenčina" },
  { apiName: "Slovenian", displayName: "Slovenščina" },
  { apiName: "Somali", displayName: "Soomaali" },
  { apiName: "Spanish", displayName: "Español" },
  { apiName: "Sundanese", displayName: "Basa Sunda" },
  { apiName: "Susu", displayName: "Susu" },
  { apiName: "Swahili", displayName: "Kiswahili" },
  { apiName: "Swati", displayName: "SiSwati" },
  { apiName: "Swedish", displayName: "Svenska" },
  { apiName: "Tahitian", displayName: "Reo Tahiti" },
  { apiName: "Tajik", displayName: "Тоҷикӣ" },
  { apiName: "Tamazight", displayName: "Tamazight" },
  { apiName: "Tamazight (Tifinagh)", displayName: "ⵜⴰⵎⵣⵉⵖⵜ" },
  { apiName: "Tamil", displayName: "தமிழ்" },
  { apiName: "Tatar", displayName: "Татар" },
  { apiName: "Telugu", displayName: "తెలుగు" },
  { apiName: "Tetum", displayName: "Tetum" },
  { apiName: "Thai", displayName: "ไทย" },
  { apiName: "Tibetan", displayName: "བོད་ཡིག" },
  { apiName: "Tigrinya", displayName: "ትግርኛ" },
  { apiName: "Tiv", displayName: "Tiv" },
  { apiName: "Tok Pisin", displayName: "Tok Pisin" },
  { apiName: "Tongan", displayName: "Faka Tonga" },
  { apiName: "Tsonga", displayName: "Xitsonga" },
  { apiName: "Tswana", displayName: "Setswana" },
  { apiName: "Tulu", displayName: "ತುಳು" },
  { apiName: "Tumbuka", displayName: "Chitumbuka" },
  { apiName: "Turkish", displayName: "Türkçe" },
  { apiName: "Turkmen", displayName: "Türkmençe" },
  { apiName: "Tuvan", displayName: "Тувин" },
  { apiName: "Twi", displayName: "Twi" },
  { apiName: "Udmurt", displayName: "Удмурт" },
  { apiName: "Ukrainian", displayName: "Українська" },
  { apiName: "Urdu", displayName: "اردو" },
  { apiName: "Uyghur", displayName: "ئۇيغۇرچە" },
  { apiName: "Uzbek", displayName: "O‘zbek" },
  { apiName: "Venda", displayName: "Tshivenḓa" },
  { apiName: "Venetian", displayName: "Vèneto" },
  { apiName: "Vietnamese", displayName: "Tiếng Việt" },
  { apiName: "Waray", displayName: "Winaray" },
  { apiName: "Welsh", displayName: "Cymraeg" },
  { apiName: "Wolof", displayName: "Wolof" },
  { apiName: "Xhosa", displayName: "IsiXhosa" },
  { apiName: "Yakut", displayName: "Саха" },
  { apiName: "Yiddish", displayName: "ייִדיש" },
  { apiName: "Yoruba", displayName: "Yorùbá" },
  { apiName: "Yucatec Maya", displayName: "Maya Yucateco" },
  { apiName: "Zapotec", displayName: "Zapoteco" },
  { apiName: "Zulu", displayName: "isiZulu" },
];
