name: Build Android

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: bun install

      - name: Create keystore.properties
        run: echo "keyAlias=upload\nstoreFile=$(pwd)/src-tauri/gen/android/upload-keystore.jks\npassword=${{ secrets.KEYSTORE_PASSWORD }}" > src-tauri/gen/android/keystore.properties

      - name: Create upload-keystore.jks
        run: echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > src-tauri/gen/android/upload-keystore.jks

      - name: Run Android build
        run: bun run tauri android build --apk

      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
          asset_name: app-universal-release.apk
          asset_content_type: application/vnd.android.package-archive
